// Simple PDF generation using window.print() with specific print styles
// In a real app, we might use jspdf/html2canvas, but for this environment without adding packages,
// we will use a print-friendly CSS approach triggered by JS.

export const generatePDF = (elementId: string) => {
    const element = document.getElementById(elementId);
    if (!element) return;

    // Create a new window for printing
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
        alert('Please allow popups to export PDF');
        return;
    }

    const htmlContent = `
        <!DOCTYPE html>
        <html>
        <head>
            <title>Days on Earth - Life Report</title>
            <style>
                body { font-family: sans-serif; color: #1a2e2a; padding: 40px; }
                h1 { color: #2D4F4A; border-bottom: 2px solid #587E76; padding-bottom: 10px; }
                h2 { color: #587E76; margin-top: 30px; }
                .stat-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 30px; }
                .stat-card { border: 1px solid #ccc; padding: 15px; border-radius: 8px; background: #f9f9f9; }
                .stat-value { font-size: 24px; font-weight: bold; color: #2D4F4A; }
                .footer { margin-top: 50px; font-size: 12px; text-align: center; color: #666; }
                @media print {
                    body { -webkit-print-color-adjust: exact; }
                }
            </style>
        </head>
        <body>
            <h1>Days on Earth Report</h1>
            <p>Generated on ${new Date().toLocaleDateString()}</p>
            
            <div id="content-copy">
                ${element.innerHTML}
            </div>

            <div class="footer">
                <p>Generated by Days on Earth</p>
            </div>
            
            <script>
                // Clean up the content for print (remove buttons, etc)
                const content = document.getElementById('content-copy');
                const buttons = content.querySelectorAll('button');
                buttons.forEach(b => b.remove());
                
                // Auto print
                window.onload = () => {
                    window.print();
                    window.close();
                }
            </script>
        </body>
        </html>
    `;

    printWindow.document.write(htmlContent);
    printWindow.document.close();
};
